const COLOR_PALETTE_ACTION_TYPES = {
    LOAD_COLOR_PALETTE:'LOAD_COLOR_PALETTE',
    CHANGE_COLOR:'CHANGE_COLOR',
};

const CURRENT_COLOR__ACTION_TYPES = {
    SET_CURRENT_COLOR:'SET_CURRENT_COLOR',
};

const DEVICE_ACTION_TYPES = {
    IS_BLUETOOTH_ENABLED:'IS_BLUETOOTH_ENABLED',
    IS_DEVICE_CONNECTED:'IS_DEVICE_CONNECTED',
};

const PICTURE_ACTION_TYPES = {
    CHANGE_PICTURE_ROWS:'CHANGE_PICTURE_ROWS',
    CHANGE_PICTURE_COLUMNS:'CHANGE_PICTURE_COLUMNS',
    CHANGE_PICTURE_PIXEL_COLOR:'CHANGE_PICTURE_PIXEL_COLOR',
    CLEARER_PICTURE:'CLEARER_PICTURE',
};

const PERSIST_ACTION_TYPES = {
    LOAD_PICTURE:'LOAD_PICTURE',
    SAVE_PICTURE:'SAVE_PICTURE',
};

export const ACTION_TYPES = {
    COLOR_PALETTE_ACTION_TYPES,
    CURRENT_COLOR__ACTION_TYPES,
    DEVICE_ACTION_TYPES,
    PICTURE_ACTION_TYPES,
    PERSIST_ACTION_TYPES
};
