export const COLOR_PALETTE_ACTION_TYPES = {
    LOAD_COLOR_PALETTE: 'LOAD_COLOR_PALETTE',
    CHANGE_COLOR:'CHANGE_COLOR',
    SET_CURRENT_COLOR:'SET_CURRENT_COLOR',
    CHANGE_PICTURE_ROWS:'CHANGE_PICTURE_ROWS',
    CHANGE_PICTURE_COLUMNS:'CHANGE_PICTURE_COLUMNS',
    CHANGE_PICTURE_PIXEL_COLOR:'CHANGE_PICTURE_PIXEL_COLOR',
    LOAD_PICTURE:'LOAD_PICTURE',
    CLEARER_PICTURE:'CLEARER_PICTURE',
    SAVE_PICTURE:'SAVE_PICTURE',
};
